Добавляет выбор типа и города в режиме редактирования
htmlacademy-ecmascript/1375337-big-trip-17 pull request #11
Opened 2022-05-25 08:43 UTC by LomaevaVV

2022-05-29 16:05 UTC, Finnko requested changes

2022-05-29 16:05 UTC, Finnko commented on src/view/event-edit-view.js
> +    const oldSelectedOffers = [...this._state.offers];
Необходимо аккуратнее работать со спредом, и не перекопировать лишний раз. Это копирование излишне

2022-05-29 16:05 UTC, Finnko commented on src/view/event-edit-view.js
> +      newSelectedOffers = [...this._state.offers, offerClicked];
Логика обратная, если оффер зачекан, то мы удаляем его из массива офферов, если нет то добавляем. this._state.offers нет нужды спредить, мы изначально заводим стейт как копию, просто пуш

2022-05-29 16:05 UTC, Finnko commented on src/view/event-edit-view.js
> +      newSelectedOffers = oldSelectedOffers;
Вариант, но обычно для удаления нагляднее использовать filter

2022-05-29 16:05 UTC, Finnko commented on src/view/event-edit-view.js
> +    });
По офферам внести правки из видео

2022-05-29 21:24 UTC, LomaevaVV commented on src/view/event-edit-view.js
> +        pictures: enteredDestination ? [...enteredDestination.pictures] : [],
а вот не знаю... А не лучше перекопировать, чтобы данные хранились не ссылкой?

2022-05-30 18:06 UTC, LomaevaVV commented on src/view/event-edit-view.js
> +      offers: [],
Исправлять не стала, как обсудили

2022-05-30 20:11 UTC, merged