Добавляет генерацию и вывод данных
htmlacademy-ecmascript/1375337-big-trip-17 pull request #4
Opened 2022-05-04 12:49 UTC by LomaevaVV

2022-05-04 19:45 UTC, Finnko requested changes

2022-05-04 19:45 UTC, Finnko commented on package.json
>      "webpack-dev-server": "^4.8.1"
Все зависимости должны быть зафиксированы
```suggestion
    "webpack-dev-server": "4.8.1"
```

2022-05-04 19:45 UTC, Finnko commented on src/constants.js
> +];
Отлично что вынесла в константу

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +
Лучше придерживаться все же общепринятого mock в названии папки 🙂

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +const POINT_TYPE = ['taxi', 'bus', 'train', 'ship', 'drive', 'flight', 'check-in', 'sightseeing', 'restaurant'];
Типы уже объявлены в файле констант

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +  const getAvailableOffers = offersСatalog.find(
переменная хранит массив найденных офферов, если они есть. Стоит убрать get из названия

2022-05-04 19:45 UTC, Finnko commented on src/utils.js
> +};
Перемешивать офферы нам нигде не надо

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +
```suggestion
```

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +  const timeHourFrom = `20${getDate(19,22)}-${getDate(1,12)}-${getDate(1,31)}T${getDate(0,23)}:${getDate(0,59)}:56.845Z`;
В этот формат можно перевести непосредственно во вью. Для генерации рандомной даты лучше использовать методы dayjs add/subtract

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +    getShuffleArraySlice(getAvailableOffers.offers)
Перемешивать офферы нет нужды

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +    isFavorite: getRandomArrayElement(IS_FAVORITE),
Как альтернатива )
1 - `Math.random > 0.5`
2- `Boolean(getRandomNumber(0, 1))`

2022-05-04 19:45 UTC, Finnko commented on src/fish/event.js
> +    id: '',
Айди лучше генерить рандомный. Можно использовать для этого библиотеку nanoid

2022-05-04 19:45 UTC, Finnko commented on src/presenter/event-board-presenter.js
> +    // Array.from({ length: this.boardEvents.length}, () => render(new EventView(this.boardEvents), this.eventsListComponent.getElement()));
Здесь нам уже не нужно создавать массив из длины. this.boardEvents это уже массив, следовательно можно заменить на Array.from(this.boardEvents,....) Но в целом использовать Array.from необязательно, я бы только заменил обычный for на for of. Синтаксис короче, счетчик в данном случае не нужен

2022-05-04 19:45 UTC, Finnko commented on src/utils.js
> +  } throw new Error('Диапазон задан неверно: минимальное значение диапазона должно быть меньше максимального. Граничные значения диапазона не могут быть меньше 0.');
Необходимо разместить на след строке 
```suggestion
  } 
  throw new Error('Диапазон задан неверно: минимальное значение диапазона должно быть меньше максимального. Граничные значения диапазона не могут быть меньше 0.');
```

2022-05-04 19:45 UTC, Finnko commented on src/utils.js
> +export const calculateDateDif = (dateFrom, dateTo) => dayjs(dateTo).diff(dateFrom, 'minute');
Стоит добавить 3 опциональный параметр unit который по умолчанию будет равен 'minute'

2022-05-04 19:45 UTC, Finnko commented on src/view/event-edit-view.js
> +  if (availableOffers.length === 0) {
Офферов может не быть, лучше проверить с помощью https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Optional_chaining
```suggestion
  if (availableOffers?.length === 0) {
```

2022-05-04 19:45 UTC, Finnko commented on src/view/event-edit-view.js
> +    : [];
Дублируется логика, мы уже при генерации точки делаем эту проверку. Поэтому если офферы придут в шаблон, то только нужные (или их не будет совсем)

2022-05-04 19:45 UTC, Finnko commented on src/view/event-view.js
> +  const getFavoriteClass = isFavorite ? 'event__favorite-btn--active' : '';
Здесь хранится результат тернарного оператора. Глаголы следует использовать только в функциях
```suggestion
  const favoriteClass = isFavorite ? 'event__favorite-btn--active' : '';
```

2022-05-04 19:45 UTC, Finnko commented on src/view/event-view.js
> +  const dateToToTime = humanizeEventDate(dateTo,'HH:mm');
В целом если это выносить ошибкой не будет. Но развесистой логики не присутствует, поэтому можно это вывести сразу в шаблоне

2022-05-05 09:16 UTC, LomaevaVV commented on src/view/event-view.js
> +  const dateToToTime = humanizeEventDate(dateTo,'HH:mm');
+

2022-05-05 09:16 UTC, LomaevaVV commented on src/view/event-view.js
> +  const getFavoriteClass = isFavorite ? 'event__favorite-btn--active' : '';
принято

2022-05-05 09:17 UTC, LomaevaVV commented on src/view/event-edit-view.js
> +    : [];
оставила как есть

2022-05-05 09:19 UTC, LomaevaVV commented on src/view/event-edit-view.js
> +  if (availableOffers.length === 0) {
принято

2022-05-05 09:25 UTC, LomaevaVV commented on src/utils.js
> +export const calculateDateDif = (dateFrom, dateTo) => dayjs(dateTo).diff(dateFrom, 'minute');
да, логично)

2022-05-05 09:26 UTC, LomaevaVV commented on src/utils.js
> +  } throw new Error('Диапазон задан неверно: минимальное значение диапазона должно быть меньше максимального. Граничные значения диапазона не могут быть меньше 0.');
принято

2022-05-05 09:50 UTC, LomaevaVV commented on src/fish/event.js
> +    getShuffleArraySlice(getAvailableOffers.offers)
Оставила как есть, Кажется что так получается более приближенные к жизни варианты.

2022-05-05 09:50 UTC, LomaevaVV commented on src/utils.js
> +};
оставила как есть

2022-05-05 10:21 UTC, LomaevaVV commented on src/fish/event.js
> +    isFavorite: getRandomArrayElement(IS_FAVORITE),
ахаха, класс.

2022-05-05 19:42 UTC, merged