Революция или эволюция? (часть 1)
htmlacademy-ecmascript/1375337-big-trip-17 pull request #5
Opened 2022-05-06 12:47 UTC by LomaevaVV

---
:mortar_board: [Революция или эволюция? (часть 1)](https://up.htmlacademy.ru/ecmascript/17/user/1375337/tasks/5)

:boom: https://htmlacademy-ecmascript.github.io/1375337-big-trip-17/5/

2022-05-06 19:52 UTC, Finnko requested changes

2022-05-06 19:52 UTC, Finnko commented on src/presenter/event-board-presenter.js
>      }
Лучше весь рендеринг вынести в отдельный метод, чтобы не перегружать init. Я бы еще и рендер ивентов вынес отдельно

2022-05-06 19:52 UTC, Finnko commented on src/presenter/event-board-presenter.js
> +    // render(new EventEditView(this.#boardEvents[0]), this.#eventsListComponent.element);
Можно удалить
```suggestion
```

2022-05-06 19:52 UTC, Finnko commented on src/presenter/event-board-presenter.js
> +      this.#renderEvent(event);
Здесь лучше уже foreach использовать
```suggestion
     this.#boardEvents.forEach(this.#renderEvent)
```

2022-05-06 19:52 UTC, Finnko commented on src/utils.js
> +  const minutes = getDeclination(minutesNum, WORD_FORMS.minutes);
Все хорошо только у нас формат '05D 23H 14M' 😉

2022-05-06 19:52 UTC, Finnko commented on src/utils.js
> +  let dateDif = `${days}`;
А если дней 0 и например часов 0?

2022-05-06 19:52 UTC, Finnko commented on src/view/filter-view.js
> +      this.#element = createElement(this.template);
В шаблоне следует размапить разметку, это пригодится нам в будущем. Для этого надо вынести фильтры в константу и добавить цикл

2022-05-07 06:22 UTC, LomaevaVV commented on src/view/filter-view.js
> +      this.#element = createElement(this.template);
в 4 домашке сделаю, как договорились

2022-05-08 11:51 UTC, Finnko approved these changes

2022-05-08 11:51 UTC, merged